name: Auto Merge Dev to Main

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          from-branch: dev
          to-branch: main
          repository-owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}

      - name: Merge Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          script: |
            const pr_number = ${{ steps.cpr.outputs.pull_number }};
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: 'merge'
            });

